name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        cd public/pintograph
        npm install
        npm run build
        mv dist/pintograph.js ../js/libraries/pintograh.js
        
    - name: Deploy 
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
